# Generated by Django 3.1 on 2020-08-28 18:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('jobs', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('company_name', wagtail.core.blocks.CharBlock()), ('job_title', wagtail.core.blocks.CharBlock(required=False)), ('meta_data', wagtail.core.blocks.StructBlock([('location', wagtail.core.blocks.CharBlock()), ('start_date', wagtail.core.blocks.DateBlock(help_text='The date you started working at this location')), ('current', wagtail.core.blocks.BooleanBlock(help_text='Select if you are currently still working at this location', required=False)), ('end_date', wagtail.core.blocks.DateBlock(help_text='The date you quit working at this location', required=False))])), ('job_discription', wagtail.core.blocks.RichTextBlock())]), form_classname='jobs-list', icon='fa-briefcase'))], blank=True, verbose_name='Qualifications'),
        ),
    ]
