# Generated by Django 3.1 on 2020-08-28 18:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200828_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
