# Generated by Django 3.1 on 2020-08-28 19:44

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200828_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([], blank=True, verbose_name='Qualifications'),
        ),
    ]
