# Generated by Django 3.1 on 2020-08-28 20:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200828_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='schools',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.StructBlock([('degree', wagtail.core.blocks.CharBlock()), ('school_name', wagtail.core.blocks.CharBlock()), ('location', wagtail.core.blocks.CharBlock()), ('start_date', wagtail.core.blocks.DateBlock(help_text='The date you started attending this school')), ('current', wagtail.core.blocks.BooleanBlock(help_text='Select if you are currently still attending this school', required=False)), ('end_date', wagtail.core.blocks.DateBlock(help_text='The date you graduated from this school', required=False)), ('major', wagtail.core.blocks.CharBlock(help_text='The focus of your degree'))]))], blank=True, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skills',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.StructBlock([('skills_title', wagtail.core.blocks.CharBlock(classname='full title')), ('details', wagtail.core.blocks.RichTextBlock())]))], blank=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='specialties',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('specialty', wagtail.core.blocks.CharBlock())]))], blank=True, verbose_name='Specialties'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='jobs',
            field=wagtail.core.fields.StreamField([('job', wagtail.core.blocks.StructBlock([('company_name', wagtail.core.blocks.CharBlock()), ('job_title', wagtail.core.blocks.CharBlock()), ('location', wagtail.core.blocks.CharBlock()), ('start_date', wagtail.core.blocks.DateBlock(help_text='The date you started working at this location')), ('current', wagtail.core.blocks.BooleanBlock(help_text='Select if you are currently still working at this location', required=False)), ('end_date', wagtail.core.blocks.DateBlock(help_text='The date you quit working at this location', required=False)), ('job_discription', wagtail.core.blocks.RichTextBlock())]))], blank=True, verbose_name='Professional Experiance'),
        ),
    ]
